language: rust

language: rust

rust:
    - stable
    - nightly
    - beta

os:
    - linux

script:
    - env
    - cargo --all-features test && \
      rustup target add wasm32-unknown-unknown && \
      cargo build --target=wasm32-unknown-unknown

after_success: |
    cargo install cargo-tarpaulin
    export CODECOV_TOKEN="8622abe0-9579-4cea-93d3-9707969ef6c2"
    cargo tarpaulin --all-features --out Xml
    bash <(curl -s https://codecov.io/bash)
